name: "Unit tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unitests:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: go build ./...
      - name: Run tests
        run: make test
